from enum import IntEnum

class FailureResponseCode(IntEnum):
    NOT_LIST = ...
    ARG = ...
    PASSWORD = ...
    PERMISSION = ...
    UNKNOWN = ...
    NO_EXIST = ...
    PLAYLIST_MAX = ...
    SYSTEM = ...
    PLAYLIST_LOAD = ...
    UPDATE_ALREADY = ...
    PLAYER_SYNC = ...
    EXIST = ...

class MPDError(Exception): ...

class CommandError(MPDError):
    pass

class MPDClientBase:
    pass
